DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS prediction_query;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE prediction_query (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_data TEXT NOT NULL,
    query_data TEXT NOT NULL
);

