steps:
- name: 'docker/compose:1.28.2'
  args: [
    '-p', 'gcr.io/$PROJECT_ID/gcb-docker-compose-web-frontend:latest',
    '-f', './docker-compose.yml',
    'build', 'web_frontend'
  ]
- name: 'docker/compose:1.28.2'
  args: [
    '-p', 'gcr.io/$PROJECT_ID/gcb-docker-compose-web-api:latest',
    '-f', './docker-compose.yml',
    'build', 'web_api'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'tag',
    'web_frontend_dev_build',
    'gcr.io/$PROJECT_ID/gcb-docker-compose-web-frontend:latest'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'tag',
    'web_api_dev_build',
    'gcr.io/$PROJECT_ID/gcb-docker-compose-web-api:latest'
  ]
images: ['gcr.io/$PROJECT_ID/gcb-docker-compose-web-frontend:latest', 'gcr.io/$PROJECT_ID/gcb-docker-compose-web-api:latest']

#steps:
# Build the new docker image.
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest', '.']

#images:
#- 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest'
options:
  logging: CLOUD_LOGGING_ONLY