steps:
# Build the new docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './web_frontend','-t', 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest', './web_frontend']

images:
- 'gcr.io/$PROJECT_ID/gcb-docker-compose:latest/web_frontend'

options:
  logging: CLOUD_LOGGING_ONLY