# .github/workflows/deploy.yml
name: Deploy to Google Cloud Run 
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploying 
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: ${{ secrets.SA_EMAIL }}
          project_id: crucial-baton-369816

      - name: Building (🏗)
        run: |-
          gcloud builds submit \
            --tag gcr.io/crucial-baton-369816/fhnw-ds-hs-2022-software-engineering-group2

      # Setup gcloud CLI
      - name: Deploy (🚀)
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: fhnw-ds-hs-2022-software-engineering-group2
          image: gcr.io/crucial-baton-369816/fhnw-ds-hs-2022-software-engineering-group2
          region: europe-west6
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: crucial-baton-369816